name: Psychics
main: io.github.monun.psychics.plugin.PsychicsPlugin
api-version: '1.19'
version: $version
author: Monun
libraries:
  - io.github.monun:tap-core:4.6.2
  - io.github.monun:invfx:3.1.0
  - io.github.monun:kommand-core:2.13.0
